#------------------------------------------------------------------------------
# Build and push a Docker image constisting of
#   - Open edX Credentials service
#
# see
#  - https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
#  - https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
#  - https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
#------------------------------------------------------------------------------
name: '"Tutor Build credentials" Action For GitHub Actions'
description: 'Use Tutor to build a Docker container of credentials, and upload to AWS ECR'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  aws-ecr-repository:
    description: 'The name of the repository inside your AWS Elastic Container Registry (ECR) in which the newly created container will be uploaded and tagged. Defaults to "credentials"'
    required: false
    default: 'credentials'

outputs:
  docker-container-url:
    description: 'The URL of the AWS ECR Docker container that was created and uploaded'
    value: ${{ steps.docker-image.outputs.uri }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: setup-docker
      uses: docker/setup-buildx-action@v1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # verify that the ECR repository exists. If not, then create it.
    - name: Create the AWS ECR repository
      id: create-repository
      uses: openedx-actions/aws-ecr-create@v0.0.2
      with:
        aws-ecr-repository: ${{ inputs.aws-ecr-repository }}

    - name: Install Tutor
      id: install-tutor
      run: ./scripts/install-tutor.sh
      shell: bash

    - name: Intialize environment variables
      id: init-env
      run: |
        echo "AWS_ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> ${{ github.env }}
        echo "AWS_ECR_REPOSITORY=${{ inputs.aws-ecr-repository }}" >> ${{ github.env }}
        echo "REPOSITORY_TAG=$TUTOR_VERSION-$(date +%Y%m%d%H%M)" >> ${{ github.env }}
      shell: bash

    - name: Initialize Docker image URI
      id: init-docker-image
      run: |
        echo "DOCKER_IMAGE=${AWS_ECR_REGISTRY}/${AWS_ECR_REPOSITORY}:${REPOSITORY_TAG}" >> ${{ github.env }}
      shell: bash

    # Note: This is scaffolding. This step initialize the tutor 'env' path, which you might need
    #       if for example, you need to add Python requirements to the image
    - name: Render Tutor Config
      id: tutor-config-save
      run: tutor config save --set DOCKER_IMAGE=${DOCKER_IMAGE}
      shell: bash

    # Note: This is scaffolding. Add environment initialization stuff to this step
    #       that requires that a.) tutor is installed, and b.) the tutor environment
    #       is initialized. 
    #
    #       Example: to add requirements to a build: $(tutor config printroot)/env/build/credentials/requirements
    - name: Set Tutor-dependent environment variables
      id: tutor-environment-variables
      run: |
        echo "scaffolding for Tutor-dependent environment variables" 
      shell: bash

    - name: Install Tutor credentials plugin
      id: install-plugin
      run: |
        pip install git+https://github.com/lpm0073/tutor-contrib-credentials@v13.0.2
        tutor plugins enable credentials
        tutor config save --set CREDENTIALS_DOCKER_IMAGE=${DOCKER_IMAGE}
      shell: bash

    - name: Build the image
      id: tutor-build-image
      run: tutor images build credentials
      shell: bash

    - name: Push the image
      id: docker-push-image
      run: ./scripts/upload-to-aws-ecr.sh
      shell: bash

    - name: Docker image:tag
      id: docker-image
      run: |
        echo "::set-output name=uri::$(echo $DOCKER_IMAGE)"
      shell: bash
